Repository speedb-io/speedb, pull requests merged in 2022-11, with the labels that each got.

#171 build: support ccache and sccache in the Makefile build (#170)
  Makefile
  build_tools/build_detect_platform
Labels: Upstreamable

#215 crashtest: fix 0 value of data_block_hash_table_util_ratio (#214)
  tools/db_crashtest.py
Labels: bug

#145 memtable_list: avoid rolling back memtable flush on CF drop (#144)
  db/column_family_test.cc
  db/memtable_list.cc
Labels: Upstreamable

#224 Update README.md
  .github/new-bee-mascot-dark.gif
  README.md
Labels: documentation

#235 db_bench: Fix a bug when destructing a Benchmark with multiple db-s (#234)
  tools/db_bench_tool.cc
Labels: bug

#188 hash spd memtable
  plugin/speedb/memtable/hash_spd_rep.cc
  plugin/speedb/memtable/hash_spd_rep.h
  plugin/speedb/memtable/spdb_sort_list.h
  port/port_posix.cc
  port/port_posix.h
  tools/db_bench_tool.cc
  tools/db_crashtest.py
Labels: bug
