Repository speedb-io/speedb, pull requests merged in 2022-10, with the labels that each got.

#103 cmake: allow running the tests in parallel like in the Makefile (#102)
  CMakeLists.txt
  Makefile
  cmake/CTestRunner.cmake
Labels: Upstreamable

#175 makefile: rework the dependency graph for faster test runs startup (#…
  Makefile
  build_tools/build_detect_platform
Labels: Upstreamable

#83 71 filter policy uri
  db_stress_tool/db_stress_common.h
  db_stress_tool/db_stress_gflags.cc
  db_stress_tool/db_stress_test_base.cc
  tools/db_bench_tool.cc
  util/filter_bench.cc
Labels: enhancement, Upstreamable

#194 options: change the default value for compaction threads to 8 (#169)
  db/column_family_test.cc
  db/db_compaction_test.cc
  db/db_flush_test.cc
  db/db_impl/db_impl_compaction_flush.cc
  db/db_options_test.cc
  db/db_test.cc
  db/db_wal_test.cc
  db/deletefile_test.cc
  include/rocksdb/options.h
Labels: enhancement

#207 build: update zlib to 1.12.3 (#206)
  Makefile
Labels: build
