Repository speedb-io/speedb, pull requests merged in 2023-02, with the labels that each got.

#384 windows build failed in speedb_paired_bloom_internal files due to bad…
  plugin/speedb/memtable/hash_spd_rep.cc
  plugin/speedb/memtable/spdb_sorted_vector.h
  plugin/speedb/paired_filter/speedb_paired_bloom_internal.cc
  plugin/speedb/paired_filter/speedb_paired_bloom_internal.h
  port/win/port_win.h
Labels: build

#380 Use a NoSyncFileSystem to skip Sync/FSync to reduce test times
  CMakeLists.txt
  TARGETS
  db/db_compaction_test.cc
  db/db_with_timestamp_test_util.h
  env/env_test.cc
  include/rocksdb/file_system.h
  src.mk
  table/table_test.cc
  test_util/testutil.cc
  utilities/counted_fs.cc
  utilities/counted_fs.h
  utilities/fault_injection_fs.cc
  utilities/fault_injection_fs.h
  utilities/injection_fs.cc
  utilities/injection_fs.h
  utilities/nosync_fs.cc
  utilities/nosync_fs.h
Labels: build

#371 Paired-Bloom-Filter: Balancing rounding to batches between the bottom-most level and other levels
  plugin/speedb/paired_filter/speedb_paired_bloom.cc
  plugin/speedb/paired_filter/speedb_paired_bloom_internal.cc
  plugin/speedb/paired_filter/speedb_paired_bloom_internal.h
Labels: enhancement

#399 Makefile: Use speedb libs in `build_size` target
  Makefile
Labels: bug fix
