Repository speedb-io/speedb, pull requests merged in 2023-05, with the labels that each got.

#495 Makefile: Remove pycache artifacts after running gtest-parallel (#486)
  .gitignore
  Makefile
Labels: build

#489 AVX512: fix disabling other optimizations
  util/xxhash.h
Labels: bug fix

#498 Stress error utf 8 codec cant decode byte
  db_stress_tool/no_batched_ops_stress.cc
Labels: Upstreamable, bug fix

#511 Have all traces to log in compaction job report both the cf name and job id (#494)
  db/compaction/compaction_job.cc
Labels: Upstreamable

#525 update HISTORY.md
  HISTORY.md
Labels: documentation

#499 WC: fix for stop while shutting down
  HISTORY.md
  db/column_family.h
  db/db_impl/db_impl_write.cc
  db/db_test.cc
  db/db_test_util.cc
  db/db_test_util.h
  db/write_controller.cc
  db/write_controller.h
Labels: bug fix

#514 Transaction test unlock wal fix
  HISTORY.md
  utilities/transactions/transaction_test.cc
Labels: bug fix
