Repository speedb-io/speedb, pull requests merged in 2023-04, with the labels that each got.

#451 dynamic delay: fix pending bytes rate calculation
  db/column_family.cc
Labels: bug fix

#427 Adding beezcli
  include/rocksdb/ldb_tool.h
  include/rocksdb/utilities/ldb_cmd.h
  monitoring/histogram.h
  monitoring/histogram_windowing.h
  tools/CMakeLists.txt
  tools/beezcli.cc
  tools/ldb_cmd.cc
  tools/ldb_cmd_impl.h
  tools/ldb_test.py
  tools/ldb_tool.cc
Labels: enhancement, usability, To review, bug fix

#387 Add Filter::CreateFromString to Java
  java/rocksjni/config_options.cc
  java/rocksjni/filter.cc
  java/rocksjni/portal.h
  java/src/main/java/org/rocksdb/ConfigOptions.java
  java/src/main/java/org/rocksdb/Filter.java
  java/src/test/java/org/rocksdb/FilterTest.java
  plugin/speedb/java/src/test/java/org/rocksdb/SpeedbFilterTest.java
  plugin/speedb/speedb.mk
Labels: Upstreamable, usability
