Repository speedb-io/speedb, pull requests merged in 2023-12, with the labels that each got.

#789 HISTORY: Update HISTORY.md for 8.6.7 rebase
  HISTORY.md
Labels: documentation

#792 Options: Set compaction_readahead_size default to 0
  HISTORY.md
  include/rocksdb/options.h
Labels: compaction

#790 Revert "added exit 0 to the license check"
  .github/workflows/check_license_and_history.yml
Labels: ci

#794 fix CI failure after changing compation_readahead_size default to 0
  HISTORY.md
  db/db_options_test.cc
  file/prefetch_test.cc
Labels: tests, ci, bug fix

#791 Options: Set level_compaction_dynamic_level_bytes as false by default
  HISTORY.md
  include/rocksdb/advanced_options.h
Labels: compaction

#788 Compaction: Restore SetupForCompaction functionality
  HISTORY.md
  table/block_based/block_based_table_reader.cc
Labels: bug fix
