Repository speedb-io/speedb, pull requests merged in 2023-08, with the labels that each got.

#611 unit tests: fix DisableMultiManualCompaction in db_compaction_test
  HISTORY.md
  db/db_compaction_test.cc
Labels: bug fix

#547 Snapshot Optimization (https://github.com/speedb-io/speedb/issues/35)
  CMakeLists.txt
  HISTORY.md
  cmake/modules/FindFolly.cmake
  db/db_impl/db_impl.cc
  db/db_impl/db_impl.h
  db/db_test2.cc
  db/snapshot_impl.h
Labels: enhancement

#638 CI: fix check license by comparing the right sha
  .github/workflows/check_license_and_history.yml
Labels: bug fix

#629 Add on thread start callback
  HISTORY.md
  build_tools/check-sources.sh
  db/db_basic_test.cc
  db/db_impl/db_impl_open.cc
  db/db_impl/db_spdb_impl_write.h
  env/env_posix.cc
  examples/.gitignore
  examples/CMakeLists.txt
  examples/Makefile
  examples/on_thread_start_callback_example.cc
  include/rocksdb/db.h
  include/rocksdb/env.h
  include/rocksdb/memtablerep.h
  include/rocksdb/options.h
  include/rocksdb/port_defs.h
  include/rocksdb/write_buffer_manager.h
  memtable/spdb_sorted_vector.h
  memtable/write_buffer_manager.cc
  options/options_settable_test.cc
  port/port_posix.cc
  port/port_posix.h
  port/win/port_win.cc
  port/win/port_win.h
Labels: enhancement

#654 Update HISTORY.md for 2.6.0
  HISTORY.md
Labels: documentation

#652 db_bench: fix SeekRandomWriteRandom valid check
  HISTORY.md
  tools/db_bench_tool.cc
Labels: bug fix
