Repository speedb-io/speedb, pull requests merged in 2024-01, with the labels that each got.

#796 stress test: Fix TestIterateAgainstExpected not supporting 0 iterations
  HISTORY.md
  tools/db_crashtest.py
Labels: bug fix

#765 fix conflicts between db_bench flags and enable speedb features flag
  HISTORY.md
  include/rocksdb/options.h
  options/options_test.cc
  tools/db_bench_tool.cc
Labels: bug fix

#803 Add more checks for db_stress enable speedb features
  HISTORY.md
  db_stress_tool/db_stress_test_base.cc
Labels: tests

#757 memory reporting
  CMakeLists.txt
  HISTORY.md
  build_tools/build_detect_platform
  db/arena_wrapped_db_iter.cc
  db/db_impl/db_impl.cc
  db/file_indexer.cc
  db/memtable.cc
  db/version_set.cc
  db/version_set_test.cc
  logging/log_buffer.cc
  memory/allocator.h
  memory/arena.cc
  memory/arena.h
  memory/arena_test.cc
  memory/concurrent_arena.h
  memory/memory_allocator.cc
  memory/memory_allocator_impl.h
  memtable/hash_linklist_rep.cc
  memtable/hash_skiplist_rep.cc
  memtable/hash_spdb_rep.cc
  memtable/inlineskiplist.h
  memtable/skiplist.h
  memtable/skiplistrep.cc
  memtable/vectorrep.cc
  table/block_based/block_based_table_reader.cc
  table/block_based/block_prefix_index.cc
  table/block_fetcher.cc
  table/compaction_merging_iterator.cc
  table/cuckoo/cuckoo_table_reader.cc
  table/iterator.cc
  table/merging_iterator.cc
  table/plain/plain_table_bloom.cc
  table/plain/plain_table_bloom.h
  table/plain/plain_table_index.cc
  table/plain/plain_table_reader.cc
  test_util/sync_point_impl.h
  tools/db_bench_tool.cc
  util/dynamic_bloom.cc
  util/dynamic_bloom.h
  utilities/write_batch_with_index/write_batch_with_index.cc
Labels: enhancement

#811 Refresh exist iterator isnot supported in hash spdb and vector memtablerep should avoid that (#802)
  HISTORY.md
  db/arena_wrapped_db_iter.cc
  db/arena_wrapped_db_iter.h
  db/db_iterator_test.cc
  db_stress_tool/no_batched_ops_stress.cc
  include/rocksdb/iterator.h
  include/rocksdb/memtablerep.h
  memtable/hash_spdb_rep.cc
  monitoring/statistics.cc
  tools/db_crashtest.py
Labels: bug fix

#820 zlib: Update ci and Makefile using a different link
  .github/workflows/build_windows.yml
  .github/workflows/ci_pipeline.yml
  HISTORY.md
  Makefile
Labels: bug fix

#817 812 stress test error initiateflushesthread assertion fail num running flushes 0
  HISTORY.md
  db/db_impl/db_impl.h
  db/db_impl/db_impl_compaction_flush.cc
  memtable/write_buffer_manager.cc
  memtable/write_buffer_manager_test.cc
Labels: bug fix

#816 stress test: Disable IsDone assertion which fails with tracing sometimes
  HISTORY.md
  db_stress_tool/expected_state.cc
Labels: bug fix

#814 Remove some db stress non existence parameters
  HISTORY.md
  db_stress_tool/db_stress_test_base.cc
Labels: bug fix
